# Generated by Django 4.2.30 on 2026-09-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_member_rewarded_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='closed_before_end_days',
            field=models.IntegerField(default=2),
        ),
    ]
