# Generated by Django 2.2 on 2019-04-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizWordPrestige',
            fields=[
                ('game_state_id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('prestige', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
