# Generated by Django 4.2.30 on 2026-09-25 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('state', '0002_states_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('state', models.OneToOneField(db_column='game_state_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='state.states')),
                ('data', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
