# Generated by Django 4.2.30 on 2026-09-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='code',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
