# Generated by Django 4.2.30 on 2026-09-25 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_profile_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_of', to='profile.profile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='profile.profile')),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'created_at'], name='profile_fri_owner_i_bf1391_idx')],
                'unique_together': {('owner', 'friend')},
            },
        ),
    ]
