"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 2.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '8(2!ig1y%(52bj7mg7_608_ww7&9(j0_nr7s1dxe(r53w6s+h8'

# SECURITY WARNING: don't run with debug turned on in production!
# С DEBUG=True любая 500-ка отдаёт наружу трейсбек с кодом и настройками,
# включая секретные ключи. Для локальной отладки: DJANGO_DEBUG=1.
DEBUG = os.environ.get('DJANGO_DEBUG') == '1'

ALLOWED_HOSTS = ['*']

# Ключ для служебных запросов: сохранение состояния и чистка таблиц.
# Был захардкожен по месту в state/views.py — теперь одно значение
# на весь проект, с возможностью подменить через окружение.
API_SECRET_KEY = os.environ.get('API_SECRET_KEY', '9012qw9012')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'prestige',
    'answer_counter',
    'likes',
    'state',
    'quiz_word',
    'metrics',
    'tutorial',
    'feedback',
    'tournament',
    'purchase',
]

# Ключ сервисного аккаунта для проверки покупок в Google Play.
# Файл кладётся на сервер отдельно и в репозиторий не попадает: это
# доступ к Play Console, а не настройка. Не найден — проверка покупок
# отвечает, что подтвердить нечем, и товар не выдаётся.
#
# Путь берём из переменной окружения, а если её нет — ищем ключ рядом
# с проектом сами. Переменная из WSGI-файла доходит не всегда, и молча
# неработающая проверка покупок — худший вид поломки: клиент считает,
# что сервер недоступен, и товар не выдаёт.
def _find_service_account_file():
    from_env = os.environ.get("GOOGLE_SERVICE_ACCOUNT_FILE", "")
    if from_env and os.path.exists(from_env):
        return from_env

    # Домашняя папка сервера: BASE_DIR — это сам проект, ключ лежит
    # уровнем выше, вне репозитория
    home = os.path.dirname(BASE_DIR)
    try:
        names = sorted(os.listdir(home))
    except OSError:
        return ""

    # Ключ Google назван по номеру проекта: api-<цифры>-<хэш>.json
    for name in names:
        if name.startswith("api-") and name.endswith(".json"):
            return os.path.join(home, name)

    return ""


GOOGLE_SERVICE_ACCOUNT_FILE = _find_service_account_file()

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = True


STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
