# Generated by Django 4.2.30 on 2026-09-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='states',
            name='platform',
            field=models.CharField(blank=True, default='google', max_length=20),
        ),
    ]
